spring:
  application:
    name: SpringBootWithoutLombok
  datasource:
    url: jdbc:postgresql://213.5.111.52:54321/SpringStudy
    username: postgres
    password: 15948Post
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    cache: false
    charset: UTF-8
    check-template-location: true
    template-loader-path: classpath:/templates/
    suffix: .ftlh